on: push

name: Integration Tests
jobs:
  # build_docs:
  #   name: ${{ matrix.python_version }} build docs
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python_version: ["3.6", "3.7", "3.8"]
  #   steps:
  #     - name: Set up python ${{ matrix.python_version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python_version }}
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build featuretools package
  #       run: make package_featuretools
  #     - name: Install featuretools with doc requirements
  #       run: |
  #         sudo apt update
  #         sudo apt install -y pandoc
  #         sudo apt install -y graphviz
  #         sudo apt install -y openjdk-11-jre-headless
  #         JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
  #         pip config --site set global.progress_bar off
  #         python -m pip install --upgrade pip
  #         python -m pip install -r unpacked_sdist/dev-requirements.txt
  #     - name: Build docs
  #       run: make -C docs/ -e "SPHINXOPTS=-W" clean html

  # install_ft_complete:
  #   name: ${{ matrix.python_version }} install featuretools complete
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python_version: ["3.6", "3.7", "3.8"]        
  #   steps:
  #     - name: Set up python ${{ matrix.python_version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python_version }}
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build featuretools package
  #       run: make package_featuretools
  #     - name: Install complete version of featuretools
  #       run: |
  #         pip config --site set global.progress_bar off
  #         python -m pip install --upgrade pip
  #         python -m pip install -e unpacked_sdist/[complete]
  #     - name: Test by importing packages
  #       run: |
  #         python -c "import featuretools_tsfresh_primitives"
  #         python -c "import featuretools_update_checker"
  #         python -c "import categorical_encoding"
  #         python -c "import nlp_primitives"
  #         python -c "import autonormalize"
  #         python -c "import featuretools_sklearn_transformer"
  #       env:
  #         FEATURETOOLS_UPDATE_CHECKER: False

  # lint_test:
  #   name: ${{ matrix.python_version }} lint test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python_version: ["3.6", "3.7", "3.8"]        
  #   steps:
  #     - name: Set up python ${{ matrix.python_version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python_version }}
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build featuretools package
  #       run: make package_featuretools
  #     - name: Install featuretools with optional, dev, and test requirements
  #       run: |
  #         pip config --site set global.progress_bar off
  #         python -m pip install --upgrade pip
  #         python -m pip install -e unpacked_sdist/[koalas]
  #         python -m pip install -r unpacked_sdist/dev-requirements.txt
  #         python -m pip install -r unpacked_sdist/test-requirements.txt
  #     - name: Run lint test
  #       run: make lint

  release_notes_updated:
    name: release notes updated
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is a pull request
        id: is_pull_request
        shell: python
        run: |
          from os.path import basename
          from re import compile

          regex =[
            '^main?',
            '^v\d+\.\d+\.\d+$',
            '^dep-update-[a-f0-9]{7}$',
          ]

          patterns = list(map(compile, regex))
          ref = basename("${{ github.event.ref }}")
          is_pull_request = not any(pattern.match(ref) for pattern in  patterns)
          value = '::set-output name=value::%s' % str(is_pull_request)
          print(value)

      - if: steps.is_pull_request.outputs.value == 'True'
        name: Check if release notes has been updatedx
        run: echo "Checking release notes"

  # unit_tests:
  #   name: ${{ matrix.python_version }} unit tests ${{ matrix.optional_libraries }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       python_version: ["3.6", "3.7", "3.8"]
  #       optional_libraries: ["minimal", "optional"]
  #   steps:
  #     - name: Set up python ${{ matrix.python_version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python_version }}
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Build featuretools package
  #       run: make package_featuretools
  #     - name: Set up pip and graphviz
  #       run: |
  #         pip config --site set global.progress_bar off
  #         python -m pip install --upgrade pip
  #         sudo apt update && sudo apt install -y graphviz
  #     - if: ${{ matrix.optional_libraries != 'optional' }}
  #       name: Install featuretools with test requirements (no optional requirements)
  #       run: |
  #         python -m pip install -e unpacked_sdist/
  #         python -m pip install -r unpacked_sdist/test-requirements.txt
  #     - if: ${{ matrix.optional_libraries == 'optional' }}
  #       name: Install featuretools with test requirements and optional requirements
  #       run: |
  #         sudo apt install -y openjdk-11-jre-headless
  #         JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
  #         python -m pip install -e unpacked_sdist/[koalas]
  #         python -m pip install -r unpacked_sdist/test-requirements.txt
  #     - if: ${{ matrix.python_version != 3.6 || matrix.optional_libraries != 'optional' }}
  #       name: Run unit tests (no code coverage)
  #       run: |
  #         cd unpacked_sdist
  #         pytest featuretools/ -n 2
  #     - if: ${{ matrix.python_version == 3.6 && matrix.optional_libraries == 'optional' }}
  #       name: Run unit tests with code coverage
  #       run: |
  #         python -m pip install "$(cat dev-requirements.txt | grep codecov)"
  #         coverage erase
  #         cd unpacked_sdist/
  #         coverage erase
  #         pytest featuretools/ -n 2 --cov=featuretools --cov-config=../.coveragerc
  #         cd ../
  #         cp unpacked_sdist/.coverage .coverage
  #         codecov --required

  # win_unit_tests:
  #   name: ${{ matrix.python_version }} windows unit tests
  #   runs-on: windows-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       python_version: ["3.6", "3.7", "3.8"]
  #   steps:
  #     - name: Setup miniconda
  #       uses: conda-incubator/setup-miniconda@v1.7.0
  #       with:
  #         auto-update-conda: true
  #         python-version: ${{ matrix.python_version }}
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #     - name: Install featuretools with test requirements
  #       shell: pwsh
  #       run: |
  #         conda config --add channels conda-forge
  #         conda install python-graphviz -q -y
  #         python -m pip install --upgrade pip
  #         python -m pip install .
  #         python -m pip install -r test-requirements.txt
  #     - name: Run unit tests
  #       run: pytest featuretools\ -n 2
