# This workflow will install dependenies and if any critical dependencies have changed a pull request
# will be created which will trigger a CI run with the new dependencies.

name: Latest Dependency Checker
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    if: ${{ github.repository_owner == 'alteryx' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Update dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dask,spark,test]"
          make checkdeps OUTPUT_PATH=featuretools/tests/requirement_files/latest_requirements.txt
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: Update latest dependencies
          title: Automated Latest Dependency Updates
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: "This is an auto-generated PR with **latest** dependency updates.
                Please do not delete the `latest-dep-update` branch because it's needed by the auto-dependency bot."
          branch: latest-dep-update
          branch-suffix: short-commit-hash
          base: main
          assignees: machineFL
          reviewers: machineAYX
