on:
  release:
    types: [published]

name: Release
jobs:
  pypi:
    name: PyPI Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyPI Upload
      uses: FeatureLabs/gh-action-pypi-upload@v2
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TEST_PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
    - name: Run workflow to create feedstock pull request
      run: |
        gh workflow run create_feedstock_pr.yaml --repo "alteryx/featuretools" -f version=${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
